# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d92af36834994b67a21c5e62f14870a0e47ebcc463f8b03c2cc6e21a8b28ca61c4fb1d89784618ed3baf61c15ce5264c282163d827f39c64adb34532a7d2c781

test:
  secret_key_base: 6aa2ed24f4c38c60987fccc5f69a5f863bcd88308d4ed223c4701504d3ba5bab037aa23f720c7e5b6264c118aa05a328f7fc73b57edcee87cd8d15c737734cbb

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
